# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import replication_pb2 as replication__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in replication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplicationServiceStub(object):
    """Peer-to-peer replication service between replica servers
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReplicateWrite = channel.unary_unary(
                '/replication.ReplicationService/ReplicateWrite',
                request_serializer=replication__pb2.ReplicateWriteRequest.SerializeToString,
                response_deserializer=replication__pb2.ReplicateWriteResponse.FromString,
                _registered_method=True)
        self.ReplicateCreate = channel.unary_unary(
                '/replication.ReplicationService/ReplicateCreate',
                request_serializer=replication__pb2.ReplicateCreateRequest.SerializeToString,
                response_deserializer=replication__pb2.ReplicateCreateResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/replication.ReplicationService/Heartbeat',
                request_serializer=replication__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=replication__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetClusterInfo = channel.unary_unary(
                '/replication.ReplicationService/GetClusterInfo',
                request_serializer=replication__pb2.GetClusterInfoRequest.SerializeToString,
                response_deserializer=replication__pb2.GetClusterInfoResponse.FromString,
                _registered_method=True)
        self.SyncState = channel.unary_unary(
                '/replication.ReplicationService/SyncState',
                request_serializer=replication__pb2.SyncStateRequest.SerializeToString,
                response_deserializer=replication__pb2.SyncStateResponse.FromString,
                _registered_method=True)
        self.AnnounceLeader = channel.unary_unary(
                '/replication.ReplicationService/AnnounceLeader',
                request_serializer=replication__pb2.AnnounceLeaderRequest.SerializeToString,
                response_deserializer=replication__pb2.AnnounceLeaderResponse.FromString,
                _registered_method=True)


class ReplicationServiceServicer(object):
    """Peer-to-peer replication service between replica servers
    """

    def ReplicateWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnounceLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReplicateWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateWrite,
                    request_deserializer=replication__pb2.ReplicateWriteRequest.FromString,
                    response_serializer=replication__pb2.ReplicateWriteResponse.SerializeToString,
            ),
            'ReplicateCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateCreate,
                    request_deserializer=replication__pb2.ReplicateCreateRequest.FromString,
                    response_serializer=replication__pb2.ReplicateCreateResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=replication__pb2.HeartbeatRequest.FromString,
                    response_serializer=replication__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetClusterInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterInfo,
                    request_deserializer=replication__pb2.GetClusterInfoRequest.FromString,
                    response_serializer=replication__pb2.GetClusterInfoResponse.SerializeToString,
            ),
            'SyncState': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncState,
                    request_deserializer=replication__pb2.SyncStateRequest.FromString,
                    response_serializer=replication__pb2.SyncStateResponse.SerializeToString,
            ),
            'AnnounceLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceLeader,
                    request_deserializer=replication__pb2.AnnounceLeaderRequest.FromString,
                    response_serializer=replication__pb2.AnnounceLeaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replication.ReplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('replication.ReplicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicationService(object):
    """Peer-to-peer replication service between replica servers
    """

    @staticmethod
    def ReplicateWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/ReplicateWrite',
            replication__pb2.ReplicateWriteRequest.SerializeToString,
            replication__pb2.ReplicateWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/ReplicateCreate',
            replication__pb2.ReplicateCreateRequest.SerializeToString,
            replication__pb2.ReplicateCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/Heartbeat',
            replication__pb2.HeartbeatRequest.SerializeToString,
            replication__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/GetClusterInfo',
            replication__pb2.GetClusterInfoRequest.SerializeToString,
            replication__pb2.GetClusterInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/SyncState',
            replication__pb2.SyncStateRequest.SerializeToString,
            replication__pb2.SyncStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnnounceLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/AnnounceLeader',
            replication__pb2.AnnounceLeaderRequest.SerializeToString,
            replication__pb2.AnnounceLeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
