# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fs_pb2 as fs__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AFSFileSystemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/afs.AFSFileSystem/Create',
                request_serializer=fs__pb2.CreateRequest.SerializeToString,
                response_deserializer=fs__pb2.CreateResponse.FromString,
                _registered_method=True)
        self.Open = channel.unary_unary(
                '/afs.AFSFileSystem/Open',
                request_serializer=fs__pb2.OpenRequest.SerializeToString,
                response_deserializer=fs__pb2.OpenResponse.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/afs.AFSFileSystem/Close',
                request_serializer=fs__pb2.CloseRequest.SerializeToString,
                response_deserializer=fs__pb2.CloseResponse.FromString,
                _registered_method=True)
        self.TestVersionNumber = channel.unary_unary(
                '/afs.AFSFileSystem/TestVersionNumber',
                request_serializer=fs__pb2.TestVersionRequest.SerializeToString,
                response_deserializer=fs__pb2.TestVersionResponse.FromString,
                _registered_method=True)


class AFSFileSystemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Open(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestVersionNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AFSFileSystemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=fs__pb2.CreateRequest.FromString,
                    response_serializer=fs__pb2.CreateResponse.SerializeToString,
            ),
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=fs__pb2.OpenRequest.FromString,
                    response_serializer=fs__pb2.OpenResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=fs__pb2.CloseRequest.FromString,
                    response_serializer=fs__pb2.CloseResponse.SerializeToString,
            ),
            'TestVersionNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.TestVersionNumber,
                    request_deserializer=fs__pb2.TestVersionRequest.FromString,
                    response_serializer=fs__pb2.TestVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'afs.AFSFileSystem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('afs.AFSFileSystem', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AFSFileSystem(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/afs.AFSFileSystem/Create',
            fs__pb2.CreateRequest.SerializeToString,
            fs__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/afs.AFSFileSystem/Open',
            fs__pb2.OpenRequest.SerializeToString,
            fs__pb2.OpenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/afs.AFSFileSystem/Close',
            fs__pb2.CloseRequest.SerializeToString,
            fs__pb2.CloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestVersionNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/afs.AFSFileSystem/TestVersionNumber',
            fs__pb2.TestVersionRequest.SerializeToString,
            fs__pb2.TestVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
