# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: snapshot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'snapshot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esnapshot.proto\x12\tsnapshots\"7\n\rMarkerMessage\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\t\"8\n\x0eMarkerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"m\n\x10LocalStateReport\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\x12\x12\n\nprocess_id\x18\x02 \x01(\t\x12\x18\n\x10serialized_state\x18\x03 \x01(\x0c\x12\x16\n\x0e\x63hannel_states\x18\x04 \x01(\x0c\"8\n\x0eReportResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"@\n\x13SnapshotCompleteMsg\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x66s_filename\x18\x02 \x01(\t\"&\n\x13SnapshotCompleteAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xfa\x01\n\x0fSnapshotService\x12\x43\n\nSendMarker\x12\x18.snapshots.MarkerMessage\x1a\x19.snapshots.MarkerResponse\"\x00\x12L\n\x10ReportLocalState\x12\x1b.snapshots.LocalStateReport\x1a\x19.snapshots.ReportResponse\"\x00\x12T\n\x10SnapshotComplete\x12\x1e.snapshots.SnapshotCompleteMsg\x1a\x1e.snapshots.SnapshotCompleteAck\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'snapshot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKERMESSAGE']._serialized_start=29
  _globals['_MARKERMESSAGE']._serialized_end=84
  _globals['_MARKERRESPONSE']._serialized_start=86
  _globals['_MARKERRESPONSE']._serialized_end=142
  _globals['_LOCALSTATEREPORT']._serialized_start=144
  _globals['_LOCALSTATEREPORT']._serialized_end=253
  _globals['_REPORTRESPONSE']._serialized_start=255
  _globals['_REPORTRESPONSE']._serialized_end=311
  _globals['_SNAPSHOTCOMPLETEMSG']._serialized_start=313
  _globals['_SNAPSHOTCOMPLETEMSG']._serialized_end=377
  _globals['_SNAPSHOTCOMPLETEACK']._serialized_start=379
  _globals['_SNAPSHOTCOMPLETEACK']._serialized_end=417
  _globals['_SNAPSHOTSERVICE']._serialized_start=420
  _globals['_SNAPSHOTSERVICE']._serialized_end=670
# @@protoc_insertion_point(module_scope)
