# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66s.proto\x12\x03\x61\x66s\"E\n\rCreateRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x0f\n\x07seq_num\x18\x03 \x01(\x03\"M\n\x0e\x43reateResponse\x12\x13\n\x0b\x66ile_handle\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"A\n\x0bOpenRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x12\n\nfetch_data\x18\x03 \x01(\x08\"v\n\x0cOpenResponse\x12\x13\n\x0b\x66ile_handle\x18\x01 \x01(\x05\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\x12\x16\n\x0eserver_version\x18\x03 \x01(\x05\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x15\n\rerror_message\x18\x05 \x01(\t\"Z\n\x0c\x43loseRequest\x12\x13\n\x0b\x66ile_handle\x18\x01 \x01(\x05\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x0f\n\x07seq_num\x18\x04 \x01(\x03\"L\n\rCloseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bnew_version\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x01(\t\"&\n\x12TestVersionRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"N\n\x13TestVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t2\xef\x01\n\rAFSFileSystem\x12\x33\n\x06\x43reate\x12\x12.afs.CreateRequest\x1a\x13.afs.CreateResponse\"\x00\x12-\n\x04Open\x12\x10.afs.OpenRequest\x1a\x11.afs.OpenResponse\"\x00\x12\x30\n\x05\x43lose\x12\x11.afs.CloseRequest\x1a\x12.afs.CloseResponse\"\x00\x12H\n\x11TestVersionNumber\x12\x17.afs.TestVersionRequest\x1a\x18.afs.TestVersionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEREQUEST']._serialized_start=17
  _globals['_CREATEREQUEST']._serialized_end=86
  _globals['_CREATERESPONSE']._serialized_start=88
  _globals['_CREATERESPONSE']._serialized_end=165
  _globals['_OPENREQUEST']._serialized_start=167
  _globals['_OPENREQUEST']._serialized_end=232
  _globals['_OPENRESPONSE']._serialized_start=234
  _globals['_OPENRESPONSE']._serialized_end=352
  _globals['_CLOSEREQUEST']._serialized_start=354
  _globals['_CLOSEREQUEST']._serialized_end=444
  _globals['_CLOSERESPONSE']._serialized_start=446
  _globals['_CLOSERESPONSE']._serialized_end=522
  _globals['_TESTVERSIONREQUEST']._serialized_start=524
  _globals['_TESTVERSIONREQUEST']._serialized_end=562
  _globals['_TESTVERSIONRESPONSE']._serialized_start=564
  _globals['_TESTVERSIONRESPONSE']._serialized_end=642
  _globals['_AFSFILESYSTEM']._serialized_start=645
  _globals['_AFSFILESYSTEM']._serialized_end=884
# @@protoc_insertion_point(module_scope)
