# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import snapshot_pb2 as snapshot__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in snapshot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SnapshotServiceStub(object):
    """--- Chandy-Lamport Snapshot Protocol ---
    Used for communication between processes participating in a global snapshot.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMarker = channel.unary_unary(
                '/snapshots.SnapshotService/SendMarker',
                request_serializer=snapshot__pb2.MarkerMessage.SerializeToString,
                response_deserializer=snapshot__pb2.MarkerResponse.FromString,
                _registered_method=True)
        self.ReportLocalState = channel.unary_unary(
                '/snapshots.SnapshotService/ReportLocalState',
                request_serializer=snapshot__pb2.LocalStateReport.SerializeToString,
                response_deserializer=snapshot__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.SnapshotComplete = channel.unary_unary(
                '/snapshots.SnapshotService/SnapshotComplete',
                request_serializer=snapshot__pb2.SnapshotCompleteMsg.SerializeToString,
                response_deserializer=snapshot__pb2.SnapshotCompleteAck.FromString,
                _registered_method=True)


class SnapshotServiceServicer(object):
    """--- Chandy-Lamport Snapshot Protocol ---
    Used for communication between processes participating in a global snapshot.

    """

    def SendMarker(self, request, context):
        """A process sends a MARKER to all its outgoing channels.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportLocalState(self, request, context):
        """After recording local state, a process sends its report to the initiator.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnapshotComplete(self, request, context):
        """The initiator notifies all participants that the snapshot is complete
        and stored in the DFS.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SnapshotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMarker': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMarker,
                    request_deserializer=snapshot__pb2.MarkerMessage.FromString,
                    response_serializer=snapshot__pb2.MarkerResponse.SerializeToString,
            ),
            'ReportLocalState': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportLocalState,
                    request_deserializer=snapshot__pb2.LocalStateReport.FromString,
                    response_serializer=snapshot__pb2.ReportResponse.SerializeToString,
            ),
            'SnapshotComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotComplete,
                    request_deserializer=snapshot__pb2.SnapshotCompleteMsg.FromString,
                    response_serializer=snapshot__pb2.SnapshotCompleteAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'snapshots.SnapshotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('snapshots.SnapshotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SnapshotService(object):
    """--- Chandy-Lamport Snapshot Protocol ---
    Used for communication between processes participating in a global snapshot.

    """

    @staticmethod
    def SendMarker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snapshots.SnapshotService/SendMarker',
            snapshot__pb2.MarkerMessage.SerializeToString,
            snapshot__pb2.MarkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportLocalState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snapshots.SnapshotService/ReportLocalState',
            snapshot__pb2.LocalStateReport.SerializeToString,
            snapshot__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SnapshotComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snapshots.SnapshotService/SnapshotComplete',
            snapshot__pb2.SnapshotCompleteMsg.SerializeToString,
            snapshot__pb2.SnapshotCompleteAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
